name:                id3cp1251fix
version:             0.1.0.0
#synopsis:
description:         Utility for decoding CP1251 ID3 tags to UTF8
homepage:            https://github.com/mikeyuriev/id3cp1251fix#readme
license:             BSD3
author:              Mike Yuriev
maintainer:          mikeyuriev@gmail.com
copyright:           2021 Mike Yuriev
category:            Utils
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- encoding >= 0.8
- htaglib >= 1.2 && < 2
- glob-posix >= 0.2
- text >= 1.2 && < 2

executables:
  id3cp1251fix:
    source-dirs:      src
    main:             Main.hs
